export const keys = [
  { value: 'AC', name: 'clear' },
  { value: '0', name: 'zero' },
  { value: '.', name: 'decimal' },
  { value: '=', name: 'equals' },
  { value: '+', name: 'add' },
  { value: '1', name: 'one' },
  { value: '2', name: 'two' },
  { value: '3', name: 'three' },
  { value: '4', name: 'four' },
  { value: '5', name: 'five' },
  { value: '6', name: 'six' },
  { value: '/', name: 'divide' },
  { value: '-', name: 'subtract' },
  { value: '7', name: 'seven' },
  { value: '8', name: 'eight' },
  { value: '9', name: 'nine' },
  { value: 'X', name: 'multiply' },
];
